#!/usr/bin/env bash
# configures a server to listening on port 80 of all servers active IPv4 IPs

# creates a symbolic link between the Nginx config file & the enabled site's dir
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx start
# terminate the first nginx process ID
kill "$(pgrep 'nginx' | head -1)"
